### ISSUE TITLE
您好，请问这个UI可以和uniapp一起使用吗

### ISSUE THREAD

**Issue by TOP-LH** [jd-ftf/wot-design-mini#221]
您好，请问这个UI可以和uniapp一起使用吗，uniapp的easycom会自动剔除掉没有的组件，这样就没必要将编译之后框架放到项目下了。

**Comment by TT1228** [comment]
你想要啥直接往里复制然后引用不就行了，我记得uniapp里uni-ui的cli里本来就集成了很多别的ui

**Comment by TOP-LH** [comment]
> 你想要啥直接往里复制然后引用不就行了，我记得uniapp里uni-ui的cli里本来就集成了很多别的ui

不是呀，单纯的CLI是纯洁的，你指的是uniapp自家的uni-ui？那个没有一点动画，那还算得上是UI吗

**Comment by TT1228** [comment]
![9CFC3C69-6451-4f38-BC6E-9A9FF2DF41CA](https://user-images.githubusercontent.com/22065144/101719022-6f095c80-3add-11eb-9fc8-e4d5b7202983.png)
![2B6D42D4-831A-4bdd-A219-9BDD3182209D](https://user-images.githubusercontent.com/22065144/101719025-716bb680-3add-11eb-83e6-2d2d2843c8bd.png)
我不确定你的意思是什么，这是我用HBuilderX初始化的一个uni-ui模板，可以看到里面缝合了很多别人的组件（而且都有.wxml和.vue两种文件），所以你想用别的资源不是把这个ui里你需要的组件往里复制然后自己引用吗

**Comment by TOP-LH** [comment]
> ![9CFC3C69-6451-4f38-BC6E-9A9FF2DF41CA](https://user-images.githubusercontent.com/22065144/101719022-6f095c80-3add-11eb-9fc8-e4d5b7202983.png)
> ![2B6D42D4-831A-4bdd-A219-9BDD3182209D](https://user-images.githubusercontent.com/22065144/101719025-716bb680-3add-11eb-83e6-2d2d2843c8bd.png)
> 我不确定你的意思是什么，这是我用HBuilderX初始化的一个uni-ui模板，可以看到里面缝合了很多别人的组件（而且都有.wxml和.vue两种文件），所以你想用别的资源不是把这个ui里你需要的组件往里复制然后自己引用吗

我的意思是，我能能否在uniapp框架里，通过npm下载wot-design-mini，然后在通过uniapp的 [easycom](https://uniapp.dcloud.io/collocation/pages?id=easycom)自动引入，以及我能否在框架里使用双向绑定功能，谢谢

**Comment by Gkxie** [comment]
> 您好，请问这个UI可以和uniapp一起使用吗，uniapp的easycom会自动剔除掉没有的组件，这样就没必要将编译之后框架放到项目下了。

[wot-design-mini](https://ftf.jd.com/wot-design-mini/#/components/introduction)没有专门为uniapp做过配置，此UI组件库是以微信小程序**自定义组件**的方式接入的，本质上来讲和你自己写的自定义组件没啥区别。
在uniapp中如何引用微信小程序自定义组件请参考其社区提供的方案。

**Comment by TOP-LH** [comment]
> > 您好，请问这个UI可以和uniapp一起使用吗，uniapp的easycom会自动剔除掉没有的组件，这样就没必要将编译之后框架放到项目下了。
> 
> [wot-design-mini](https://ftf.jd.com/wot-design-mini/#/components/introduction)没有专门为uniapp做过配置，此UI组件库是以微信小程序**自定义组件**的方式接入的，本质上来讲和你自己写的自定义组件没啥区别。
> 在uniapp中如何引用微信小程序自定义组件请参考其社区提供的方案。

哎，难得看到这么宝藏的UI框架。后续可能会兼容uniapp吗？

**Comment by Gkxie** [comment]
换句话来说，如果uniapp能够兼容vant这样的ui组件库，那么它也是兼容wot-design-mini的，因为wot-design-mini和vant在技术层面是完全相同性质的组件库。
