### ISSUE TITLE
组件按钮设置disabled以后样式改变但是点击事件仍可触发

### ISSUE THREAD

**Issue by TT1228** [jd-ftf/wot-design-mini#224]
请问一下这是一个bug还是特意设计成如此，这样使用组件时还要给他额外绑定style，指定pointer-events，感觉没有体现出组件易用性

**Comment by yawuling** [comment]
辛苦提供下使用的版本，这边看是正常的没有问题的

**Comment by TT1228** [comment]
> 辛苦提供下使用的版本，这边看是正常的没有问题的

问题我自己解决了，我想当然地在`<wd-button>`上bind:tap，而不是bind:click，使得组件没有拦截到点击事件，外层tap一直在触发，谢谢，很好的组件

**Comment by yawuling** [comment]
好的，那我将 issue 关掉，感谢对我们组件的支持～
